astrid_weather_homepage:
    path:     /
    defaults: { _controller: astridWeatherBundle:Weather:index }

astrid_weather_idweather:
    path:     /idweather/{id}
    defaults: { _controller: astridWeatherBundle:Weather:idWeather }

astrid_weather_newcity:
    path:     /newcity
    defaults: { _controller: astridWeatherBundle:Weather:nameWeather }


astrid_weather_geoloc:
    path:     /geoloc
    defaults: { _controller: astridWeatherBundle:Weather:coordWeather }

astrid_weather_delete:
    path:     /delete/{id}
    defaults: { _controller: astridWeatherBundle:Weather:delete }

astrid_weather_idforecast:
    path:     /idforecast/{id}
    defaults: { _controller: astridWeatherBundle:Forecast:idForecast }

astrid_weather_geoloc_forecast:
    path:     /geoloc-forecast
    defaults: { _controller: astridWeatherBundle:Forecast:coordForecast }