<?php

namespace astrid\WeatherBundle\Repository;

use astrid\WeatherBundle\Entity\City;
use Doctrine\ORM\EntityRepository;

/**
 * CachedweatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CachedweatherRepository extends EntityRepository
{
	public function findCachedForecast(City $city) {
		$qb = $this->createQueryBuilder('c');

		$qb->where('c.city = :city')
			->setParameter('city', $city)
			->andWhere($qb->expr()->like('c.day', "'f%'"));

		return $qb->getQuery()->getResult();
	}
}
