<?php

namespace astrid\WeatherBundle\Repository;

/**
 * CachedweatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CachedweatherRepository extends \Doctrine\ORM\EntityRepository
{
}
